# Generated by Django 3.0.3 on 2020-03-05 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.CharField(max_length=128)),
                ('currentPossessor', models.IntegerField(default=0)),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='DEFAULT TITLE', max_length=50)),
                ('description', models.CharField(default='DEFAULT DESCRIPTION', max_length=500)),
                ('x_cor', models.IntegerField(default=0)),
                ('y_cor', models.IntegerField(default=0)),
                ('max_exits', models.IntegerField(default=4)),
                ('current_exits', models.IntegerField(default=0)),
                ('east', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='east_exit', to='adventure.Room')),
                ('north', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='north_exit', to='adventure.Room')),
                ('south', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='south_exit', to='adventure.Room')),
                ('west', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='west_exit', to='adventure.Room')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('current_room', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='adventure.Room')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
