# Generated by Django 3.0.3 on 2020-03-04 17:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.CharField(max_length=128)),
                ('currentPossessor', models.IntegerField(default=0)),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='room',
            old_name='e_to',
            new_name='x_cor',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='n_to',
            new_name='y_cor',
        ),
        migrations.RemoveField(
            model_name='player',
            name='currentRoom',
        ),
        migrations.RemoveField(
            model_name='room',
            name='s_to',
        ),
        migrations.RemoveField(
            model_name='room',
            name='w_to',
        ),
        migrations.AddField(
            model_name='player',
            name='current_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adventure.Room'),
        ),
        migrations.AddField(
            model_name='room',
            name='east',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='east_exit', to='adventure.Room'),
        ),
        migrations.AddField(
            model_name='room',
            name='north',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='north_exit', to='adventure.Room'),
        ),
        migrations.AddField(
            model_name='room',
            name='south',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='south_exit', to='adventure.Room'),
        ),
        migrations.AddField(
            model_name='room',
            name='west',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='west_exit', to='adventure.Room'),
        ),
    ]
