# Generated by Django 3.0.3 on 2020-03-03 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='e_to',
            new_name='east',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='n_to',
            new_name='north',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='s_to',
            new_name='south',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='w_to',
            new_name='west',
        ),
        migrations.RemoveField(
            model_name='player',
            name='currentRoom',
        ),
        migrations.AddField(
            model_name='player',
            name='current_room',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='adventure.Room'),
        ),
        migrations.AddField(
            model_name='room',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='y',
            field=models.IntegerField(default=0),
        ),
    ]
