# Generated by Django 3.0.4 on 2020-03-05 22:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(default='hallway', max_length=50),
        ),
        migrations.AddField(
            model_name='room',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='currentPossessor',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='room',
            name='max_exits',
            field=models.IntegerField(default=3),
        ),
    ]
