# Generated by Django 3.0.3 on 2020-03-03 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0004_auto_20200303_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='east',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='room',
            name='north',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='room',
            name='south',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='room',
            name='west',
            field=models.IntegerField(default=None),
        ),
    ]
