# Generated by Django 3.0.3 on 2020-03-03 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0006_auto_20200303_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='x',
            new_name='x_cor',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='y',
            new_name='y_cor',
        ),
    ]
