# Generated by Django 3.0.3 on 2020-03-04 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0007_auto_20200303_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='east',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='east_exit', to='adventure.Room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='north',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='north_exit', to='adventure.Room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='south',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='south_exit', to='adventure.Room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='west',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='west_exit', to='adventure.Room'),
        ),
    ]
